[platformio]
default_envs = smart_dj
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit VL53L0X @ ^1.2.4

[env:smart_dj]
board = esp32dev
build_src_filter =
  -<*>
  +<firmware/integrated/smart_dj.ino>

[env:vl53l0x_test]
board = esp32dev
build_src_filter =
  -<*>
  +<firmware/sensor_test/vl53l0x_test.ino>

[env:mic_test]
board = esp32dev
build_src_filter =
  -<*>
  +<firmware/sensor_test/mic_test.ino>

